vich_uploader:
    db_driver: orm

    metadata:
        type: attribute


    mappings:
        profile_pictures:
            uri_prefix: /assets/images/profile_pictures
            upload_destination: '%kernel.project_dir%/public/assets/images/profile_pictures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true